//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyTree.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("; Extended Properties =  \"Text;HDR=YES;FMT=Delimited; Excel 8.0;IMEX=1\" ")]
        public string ApplicationConnectionString {
            get {
                return ((string)(this["ApplicationConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:/Program Files/GSGALE/FamilyTree V0.96/Resources/FamilyTree.csv")]
        public string ApplicationEncryptedFilePathAndName_Deprecated {
            get {
                return ((string)(this["ApplicationEncryptedFilePathAndName_Deprecated"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("530")]
        public int ChildComboBoxSelectionHeight {
            get {
                return ((int)(this["ChildComboBoxSelectionHeight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int FamilyTreeControlLevelDepthToDisplay {
            get {
                return ((int)(this["FamilyTreeControlLevelDepthToDisplay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ApplicationTestingMode {
            get {
                return ((bool)(this["ApplicationTestingMode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Relationship_Level, DOB ASC")]
        public string FamilyTreeControlSortOrder {
            get {
                return ((string)(this["FamilyTreeControlSortOrder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ODA_32.ico")]
        public string ApplicationIconFileName {
            get {
                return ((string)(this["ApplicationIconFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FullName, Gender, DOB, Family_Name")]
        public string ChildComboBoxColumnOrder {
            get {
                return ((string)(this["ChildComboBoxColumnOrder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Family_Name ASC, DOB ASC")]
        public string ChildComboBoxSortOrder {
            get {
                return ((string)(this["ChildComboBoxSortOrder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Screening_Determination = \'CLEARED\'")]
        public string FamilyTreeControlHighlightScreeningClearences {
            get {
                return ((string)(this["FamilyTreeControlHighlightScreeningClearences"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Person_SK, Relationship_Level, Anchor_Person_SK, Family_Name, Related_Person_SK,R" +
            "elated_Person_SK_Tree,Person_SK_Tree, Relatives Cleared")]
        public string ChildComboBoxHideColumns {
            get {
                return ((string)(this["ChildComboBoxHideColumns"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FullName, Gender, DOB, Person_SK")]
        public string ChildSelectedDataGridViewSortOrder {
            get {
                return ((string)(this["ChildSelectedDataGridViewSortOrder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Person_SK, Relationship_Level, Anchor_Person_SK, Family_Name, Related_Person_SK,R" +
            "elated_Person_SK_Tree,Person_SK_Tree, Relatives Cleared")]
        public string ChildSelectedDataGridViewHideColumns {
            get {
                return ((string)(this["ChildSelectedDataGridViewHideColumns"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Department of the Premier and Cabinet")]
        public string ApplicationCreatedByDepartment {
            get {
                return ((string)(this["ApplicationCreatedByDepartment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Office for Data Analytics")]
        public string ApplicationCreatedByBusinessGroup {
            get {
                return ((string)(this["ApplicationCreatedByBusinessGroup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Child Commercial Care Family Tree")]
        public string ApplicationName {
            get {
                return ((string)(this["ApplicationName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Classified")]
        public string ApplicationClassificationLevel {
            get {
                return ((string)(this["ApplicationClassificationLevel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\GSGALE\\FamilyTree")]
        public string ApplicationInitialDirectory {
            get {
                return ((string)(this["ApplicationInitialDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("830")]
        public int ApplicationFormNormalHeight {
            get {
                return ((int)(this["ApplicationFormNormalHeight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1090")]
        public int ApplicationFormNormalWidth {
            get {
                return ((int)(this["ApplicationFormNormalWidth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("830")]
        public int ApplicationFormExtendedHeight {
            get {
                return ((int)(this["ApplicationFormExtendedHeight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Search for individuals from a known list.  Listing is Surname, First Name then Mi" +
            "ddle Name. Clear Search box for complete list.")]
        public string ChildComboBoxToolTip {
            get {
                return ((string)(this["ChildComboBoxToolTip"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Displays \'Family Tree\' of individuals related to the selected Child.  Individuals" +
            " with some form of Security Clearance are highlighted.")]
        public string FamilyTreeControlToolTip {
            get {
                return ((string)(this["FamilyTreeControlToolTip"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Displays selected child information.   ")]
        public string ChildSelectedDataGridToolTip {
            get {
                return ((string)(this["ChildSelectedDataGridToolTip"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ApplicationMaximiseButton {
            get {
                return ((bool)(this["ApplicationMaximiseButton"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Expand All")]
        public string FormExpandAllCommandButtonExpandText {
            get {
                return ((string)(this["FormExpandAllCommandButtonExpandText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Collapse All")]
        public string FormExpandAllCommandButtonCollapseText {
            get {
                return ((string)(this["FormExpandAllCommandButtonCollapseText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT * 

,Family_Name + ', ' + First_Given_Name + ' ' +  iif(Second_Given_Name IS NOT NULL, Second_Given_Name  ,"""") AS [FullName]

,Family_Name + ', ' + First_Given_Name + ' ' +  iif(Second_Given_Name IS NOT NULL, Second_Given_Name  ,"""") + iif(Relationship_Name IS NOT NULL,  ' (' + Relationship_Name + ')' ,"""") AS [FullNameWithRelationship]  

,iif(Gender_Code=""M"", ""Male"",""Female"") AS Gender

, Count_Screened_Relative AS [Relatives Cleared]

, Birth_Date AS [DOB]

, [Address_Line] + ' ' + [Suburb] + ', ' + [Post_Code] AS [Address]

, [Suburb] + ', ' + [Post_Code] AS [Address 2]

FROM")]
        public string SQL4Application {
            get {
                return ((string)(this["SQL4Application"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FullName, Gender, DOB, Relatives Cleared")]
        public string ChildSelectedDataGridViewShowColumns {
            get {
                return ((string)(this["ChildSelectedDataGridViewShowColumns"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FullName, Gender, DOB, Relatives Cleared")]
        public string ChildComboBoxShowColumns {
            get {
                return ((string)(this["ChildComboBoxShowColumns"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FullName, Gender, DOB, Relatives Cleared")]
        public string ChildSelectedDataGridViewColumnOrder {
            get {
                return ((string)(this["ChildSelectedDataGridViewColumnOrder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana")]
        public string HighlightedFont {
            get {
                return ((string)(this["HighlightedFont"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gainsboro")]
        public string HighlightedBackColour {
            get {
                return ((string)(this["HighlightedBackColour"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string HighlightedFontColour {
            get {
                return ((string)(this["HighlightedFontColour"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int HighlightedFontSize {
            get {
                return ((int)(this["HighlightedFontSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public string HighlightedFontStyle {
            get {
                return ((string)(this["HighlightedFontStyle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FullName,Gender,DOB, Address\r\n")]
        public string ClearedRelativesShowColumns {
            get {
                return ((string)(this["ClearedRelativesShowColumns"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FullName,Gender,DOB, Address, Suburb, Post_Code")]
        public string ClearedRelativesColumnOrder {
            get {
                return ((string)(this["ClearedRelativesColumnOrder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1730")]
        public int ApplicationFormExtendedWidth {
            get {
                return ((int)(this["ApplicationFormExtendedWidth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Search / Select")]
        public string FormLabelSelectChild {
            get {
                return ((string)(this["FormLabelSelectChild"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Selected Relationship Details")]
        public string FormLabelSelectedRelationships {
            get {
                return ((string)(this["FormLabelSelectedRelationships"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Identified Relationship Structure")]
        public string FormLabelRelationshipTree {
            get {
                return ((string)(this["FormLabelRelationshipTree"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Identified Relatives with Clearances")]
        public string FormLabelRelativesWithClearences {
            get {
                return ((string)(this["FormLabelRelativesWithClearences"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int FormLocationOnScreenTop {
            get {
                return ((int)(this["FormLocationOnScreenTop"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int FormLocationOnScreenLeft {
            get {
                return ((int)(this["FormLocationOnScreenLeft"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FullName, Gender, DOB, Family_Name,Person_SK, Relationship_Level, Anchor_Person_S" +
            "K, Related_Person_SK,Related_Person_SK_Tree,Person_SK_Tree, Relatives Cleared,Pe" +
            "rson_SK_Tree_ID,Related_Person_SK_Tree_ID")]
        public string ChildComboBoxDataTableColumns {
            get {
                return ((string)(this["ChildComboBoxDataTableColumns"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("boy.ico")]
        public string ApplicationMaleGenderIcon {
            get {
                return ((string)(this["ApplicationMaleGenderIcon"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("girl.ico")]
        public string ApplicationFemaleGenderIcon {
            get {
                return ((string)(this["ApplicationFemaleGenderIcon"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v1.0.3")]
        public string ApplicationCurrentVersion {
            get {
                return ((string)(this["ApplicationCurrentVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Check16.ico")]
        public string ApplicationSecurityClearenceCleared {
            get {
                return ((string)(this["ApplicationSecurityClearenceCleared"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cross16.ico")]
        public string ApplicationSecurityClearenceWarning {
            get {
                return ((string)(this["ApplicationSecurityClearenceWarning"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data successfully loaded.")]
        public string ApplicationDataSuccessfullySelectedNotificationLine1 {
            get {
                return ((string)(this["ApplicationDataSuccessfullySelectedNotificationLine1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please select an individual from the Combo Box.")]
        public string ApplicationDataSuccessfullySelectedNotificationLine2 {
            get {
                return ((string)(this["ApplicationDataSuccessfullySelectedNotificationLine2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\GSGALE\\")]
        public string ApplicationUnpackDirectory {
            get {
                return ((string)(this["ApplicationUnpackDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FamilyTreeControlMinimumAgeToDisplay {
            get {
                return ((int)(this["FamilyTreeControlMinimumAgeToDisplay"]));
            }
        }
    }
}
